
Manual process :


1. raw files --- monthly basis
2. jan raw file --- get the insight
3. feb raw fie --- get the insight -
4. lets suppose for combine output / combine insight : merging file by manual file
5. insight 

Automation Task :

1. monthly basis - files are coming
2. by using query we applied some steps.
3. we done data cleaning , data inconsistent  -- consistent
4. query saving
5. if new files are coming then from step 1-4 query is doing the task.
6. we are getting the combined clean data in the output file.

integrate with this output file python :
1. we are going to import the output file into python and then we are doing some analysis.
2. descriptive analysis
3. information about dataset
4. chrts

we are going to integrate this output file to sql by uing python. 
1. query extraction  for  further analysis.
   



process:


excel automation by query ---> python analysis ---> sql analysis ---> dashboard (excel / power )

In [1]:
import numpy as np 
import pandas as pd
import sqlalchemy # it is a python library which is used to work with the database.
from sqlalchemy import create_engine # create engine is a function which used to create bridge between python env. or database.

In [10]:
from openpyxl import load_workbook #openpyexcel is it is a python library whihc is used to work with the excel.
import pandas as pd
import os
# from docx import Document
# from docx.shared import Inches

excel_path = "Book1.xlsx"

# Load workbook and extract sheets
xls = pd.ExcelFile(excel_path)
sheet_names = xls.sheet_names

# output_dir = "/mnt/data/project_outputs"
# os.makedirs(output_dir, exist_ok=True)

# # Save all sheets separately
# saved_files = []

# for sheet in sheet_names:
#     df = pd.read_excel(excel_path, sheet_name=sheet)
#     out_path = os.path.join(output_dir, f"{sheet}.csv")
#     df.to_csv(out_path, index=False)
#     saved_files.append(out_path)

# Main project sheet
df = pd.read_excel(excel_path, sheet_name="Data_file_project")

In [11]:
df = pd.read_excel(excel_path, sheet_name="Data_file_project")

In [12]:
df

,Date,Year,Month,Category,Product,Region,Units_Sold,Unit_Price,Revenue,Profit,Cost
0,2024-01-01,2024,January,Electronics,Laptop,North,182,1360,247520,100033.06,147486.94
1,2024-01-01,2024,January,Electronics,Laptop,South,151,4272,645072,194029.57,451042.43
2,2024-01-01,2024,January,Electronics,Laptop,East,201,966,194166,82521.77,111644.23
3,2024-01-01,2024,January,Electronics,Laptop,West,167,3944,658648,197410.80,461237.20
4,2024-01-01,2024,January,Electronics,Smartphone,North,231,630,145530,64739.58,80790.42
...,...,...,...,...,...,...,...,...,...,...,...
1100,2025-05-01,2025,May,Electronics,Unknown,North,323,3449,1114027,486259.52,627767.48
1101,2025-05-01,2025,May,Electronics,Smartphone,South,114,3930,448020,122526.96,325493.04
1102,2025-05-01,2025,May,Groceries,Rice,North,233,1816,423128,86460.66,336667.34
1103,2025-05-01,2025,May,Groceries,Unknown,South,120,1160,139200,53104.39,86095.61
1104,2025-05-01,2025,May,Furniture,Chair,South,128,1212,155136,43415.47,111720.53

In [13]:
df.head()

,Date,Year,Month,Category,Product,Region,Units_Sold,Unit_Price,Revenue,Profit,Cost
0,2024-01-01,2024,January,Electronics,Laptop,North,182,1360,247520,100033.06,147486.94
1,2024-01-01,2024,January,Electronics,Laptop,South,151,4272,645072,194029.57,451042.43
2,2024-01-01,2024,January,Electronics,Laptop,East,201,966,194166,82521.77,111644.23
3,2024-01-01,2024,January,Electronics,Laptop,West,167,3944,658648,197410.80,461237.20
4,2024-01-01,2024,January,Electronics,Smartphone,North,231,630,145530,64739.58,80790.42

In [14]:
df.tail()

,Date,Year,Month,Category,Product,Region,Units_Sold,Unit_Price,Revenue,Profit,Cost
1100,2025-05-01,2025,May,Electronics,Unknown,North,323,3449,1114027,486259.52,627767.48
1101,2025-05-01,2025,May,Electronics,Smartphone,South,114,3930,448020,122526.96,325493.04
1102,2025-05-01,2025,May,Groceries,Rice,North,233,1816,423128,86460.66,336667.34
1103,2025-05-01,2025,May,Groceries,Unknown,South,120,1160,139200,53104.39,86095.61
1104,2025-05-01,2025,May,Furniture,Chair,South,128,1212,155136,43415.47,111720.53

In [18]:
df.shape

(1105, 11)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1105 entries, 0 to 1104
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Date        1105 non-null   datetime64[ns]
 1   Year        1105 non-null   int64
 2   Month       1105 non-null   object
 3   Category    1105 non-null   object
 4   Product     1105 non-null   object
 5   Region      1105 non-null   object
 6   Units_Sold  1105 non-null   int64
 7   Unit_Price  1105 non-null   int64
 8   Revenue     1105 non-null   int64
 9   Profit      1105 non-null   float64
 10  Cost        1105 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(4), object(4)
memory usage: 95.1+ KB

In [21]:
df.describe()

,Date,Year,Units_Sold,Unit_Price,Revenue,Profit,Cost
count,1105,1105.000000,1105.000000,1105.000000,1.105000e+03,1.105000e+03,1.105000e+03
mean,2024-08-31 09:52:56.470588160,2024.294118,298.090498,2739.918552,8.177646e+05,2.657361e+05,5.520286e+05
min,2024-01-01 00:00:00,2024.000000,80.000000,502.000000,4.780800e+04,1.205586e+04,3.492354e+04
25%,2024-05-01 00:00:00,2024.000000,181.000000,1625.000000,3.715470e+05,1.183682e+05,2.397007e+05
50%,2024-09-01 00:00:00,2024.000000,295.000000,2767.000000,6.827410e+05,2.198440e+05,4.654950e+05
75%,2025-01-01 00:00:00,2025.000000,406.000000,3868.000000,1.149712e+06,3.740206e+05,7.834116e+05
max,2025-05-01 00:00:00,2025.000000,644.000000,4998.000000,2.679684e+06,1.052007e+06,2.027646e+06
std,NaN,0.455851,132.647392,1291.833869,5.484034e+05,1.912102e+05,3.783437e+05

In [22]:
df.isnull().sum()

Date          0
Year          0
Month         0
Category      0
Product       0
Region        0
Units_Sold    0
Unit_Price    0
Revenue       0
Profit        0
Cost          0
dtype: int64

In [37]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1100     True
1101     True
1102     True
1103     True
1104    False
Length: 1105, dtype: bool

In [38]:
df.drop_duplicates(inplace = True)

In [39]:
df

,Date,Year,Month,Category,Product,Region,Units_Sold,Unit_Price,Revenue,Profit,Cost
0,2024-01-01,2024,January,Electronics,Laptop,North,182,1360,247520,100033.06,147486.94
1,2024-01-01,2024,January,Electronics,Laptop,South,151,4272,645072,194029.57,451042.43
2,2024-01-01,2024,January,Electronics,Laptop,East,201,966,194166,82521.77,111644.23
3,2024-01-01,2024,January,Electronics,Laptop,West,167,3944,658648,197410.80,461237.20
4,2024-01-01,2024,January,Electronics,Smartphone,North,231,630,145530,64739.58,80790.42
...,...,...,...,...,...,...,...,...,...,...,...
1096,2025-05-01,2025,May,Sports,Shoes,North,313,3338,1044794,250278.13,794515.87
1097,2025-05-01,2025,May,Sports,Shoes,South,227,1884,427668,167850.66,259817.34
1098,2025-05-01,2025,May,Sports,Shoes,East,241,3399,819159,322004.74,497154.26
1099,2025-05-01,2025,May,Sports,Shoes,West,150,4447,667050,193076.02,473973.98
1104,2025-05-01,2025,May,Furniture,Chair,South,128,1212,155136,43415.47,111720.53

In [40]:
output_df = r'C:\Users\hp\HypterClasses\Batch 2\merge_bat\project\real_world_sales_project_dataset\Data_file_project\final_data.csv'

In [41]:
df.to_csv(output_df,index=False)

In [31]:
df['Product'].unique()

array(['Laptop', 'Smartphone', 'Tablet', 'Unknown', 'Chair', 'Desk',
       'Sofa', 'T-Shirt', 'Jeans', 'Jacket', 'Rice', 'Milk', 'Snacks',
       'Football', 'Cricket Bat', 'Shoes'], dtype=object)

In [33]:
total_sales = df['Units_Sold'].sum()
total_sales

np.int64(311011)

In [42]:
import pandas as pd
from sqlalchemy import create_engine

# =========================
# MYSQL CONNECTION
# =========================

username = "root"
password = "Y1012jqkhkp"
host = "localhost"
port = "3306"
database = "sales_data"

# Create connection string
engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}"
)

# =========================
# READ CSV FILE
# =========================

# csv_file = r'Book1.xlsx'

# xls = pd.ExcelFile(excel_path)
# sheet_names = xls.sheet_names

# df = pd.read_excel(excel_path, sheet_name="Data_file_project")

df = pd.read_csv('final_data.csv')

# =========================
# STORE CSV INTO MYSQL
# =========================

table_name = "sales"

# if_exists options:
# replace -> delete old table and create new
# append  -> add new rows
# fail    -> error if table exists

df.to_sql(
    name=table_name,
    con=engine,
    if_exists="replace",
    index=False
)

print("CSV uploaded successfully!")

# =========================
# FETCH DATA FROM MYSQL
# =========================

query = f"SELECT * FROM {table_name}"

result_df = pd.read_sql(query, con=engine)

# =========================
# PRINT COLUMN NAMES
# =========================

print("\nColumn Names:")
print(result_df.columns.tolist())

# =========================
# PRINT ALL ROWS
# =========================

print("\nAll Records:")
print(result_df)

CSV uploaded successfully!

Column Names:
['Date', 'Year', 'Month', 'Category', 'Product', 'Region', 'Units_Sold', 'Unit_Price', 'Revenue', 'Profit', 'Cost']

All Records:
            Date  Year    Month     Category     Product Region  Units_Sold  \
0     2024-01-01  2024  January  Electronics      Laptop  North         182
1     2024-01-01  2024  January  Electronics      Laptop  South         151
2     2024-01-01  2024  January  Electronics      Laptop   East         201
3     2024-01-01  2024  January  Electronics      Laptop   West         167
4     2024-01-01  2024  January  Electronics  Smartphone  North         231
...          ...   ...      ...          ...         ...    ...         ...
1033  2025-05-01  2025      May       Sports       Shoes  North         313
1034  2025-05-01  2025      May       Sports       Shoes  South         227
1035  2025-05-01  2025      May       Sports       Shoes   East         241
1036  2025-05-01  2025      May       Sports       Shoes   West         150
1037  2025-05-01  2025      May    Furniture       Chair  South         128

      Unit_Price  Revenue     Profit       Cost
0           1360   247520  100033.06  147486.94
1           4272   645072  194029.57  451042.43
2            966   194166   82521.77  111644.23
3           3944   658648  197410.80  461237.20
4            630   145530   64739.58   80790.42
...          ...      ...        ...        ...
1033        3338  1044794  250278.13  794515.87
1034        1884   427668  167850.66  259817.34
1035        3399   819159  322004.74  497154.26
1036        4447   667050  193076.02  473973.98
1037        1212   155136   43415.47  111720.53

[1038 rows x 11 columns]